# Generated by Django 5.0.4 on 2024-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bio',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='salary',
            field=models.FloatField(),
        ),
    ]
