name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files
      uses: appleboy/scp-action@master
      with:
        host: "ec2-52-15-193-97.us-east-2.compute.amazonaws.com"
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ubuntu"

    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: "ec2-52-15-193-97.us-east-2.compute.amazonaws.com"
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo pkill -f runserver
          git pull
          nohup python3 manage.py runserver 0.0.0.0:8000